[format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

# Line length
# line-length = 100

[lint.flake8-quotes]
docstring-quotes = "single"
inline-quotes = "single"
multiline-quotes = "single"
