#!/bin/bash
# Pre-requesite programs:
#   git, curl, nvim, bash, python-dev, python3-dev, python3-pip
# Other useful apps:
#   apt install:
#       htop tmux cargo nfs-common python3-pynvim libssl-dev
#   rustup install:
#
#   cargo install:
#       fd-find rigprep cargo-msrv cargo-update cargo-binutils clippy

# Global list of config files to symlink
dot_files=('.bashrc' '.bash_aliases' '.git-prompt.sh' '.config/nvim/init.lua' '.tmux.conf' '.config/gdb/gdbinit')

set_dot_files(){
    # An example of how to download this repo...
    #echo git clone https://github.com/Egod3/.dotFiles.git .dotFiles

    # Check if the nvim config path exists if it does not create it
    NVIM_CONF_DIR="$HOME/.config/nvim"
    if [[ ! -d "$NVIM_CONF_DIR" ]]; then
        mkdir -vp "$NVIM_CONF_DIR"
    fi

    for i in "${dot_files[@]}"
    do
        # If there is a .bashrc file locally in ~/ then move it to ~/.bashrc.bak
        # and add a symlink to ~/.dotFiles/.bashrc
        if [[ $i == ".bashrc" ]]; then
          if [[ ! -L "$HOME/.bashrc" ]]; then
            if [[ -f "$HOME/.bashrc" ]]; then
              mv "$HOME/.bashrc" "$HOME/.bashrc.bak"
              echo "mv $HOME/.bashrc $HOME/.bashrc.bak"
            fi
            ln -s $HOME/.dotFiles/$i $HOME/$i
            echo ln -s $HOME/.dotFiles/$i $HOME/$i
          fi
        elif [[ ! -f $i ]]; then
          ln -s $HOME/.dotFiles/$i $HOME/$i
          echo ln -s $HOME/.dotFiles/$i $HOME/$i
        fi
    done
}

# Check if the config files in dot_files array above
# are symlinks if so remove them so when we run set_dot_files
# above it will test it
rm_dot_files()
{
  for i in "${dot_files[@]}"
  do
    if [[ -L "$HOME/$i" ]]; then
      rm -v $HOME/$i
    fi
  done

}

if [[ $1 == "test" ]]; then
  echo "Test flag detected, removing config files to test set_dot_files()"
  pushd $HOME/
  rm_dot_files
  popd
  echo
fi

pushd $HOME/
set_dot_files
popd
